Shrink History
mtlynch/tinypilot pull request #237
Opened 2020-09-18 02:34 UTC by djclueless

Hiding the history now frees up that 90px of screen real-estate it was using. This helps keep the modifier key buttons in view by preventing overflow.

2020-09-18 14:58 UTC, mtlynch requested changes
It's a little confusing to have `visibility: hidden` but then make it 0px in height. Doesn't `hidden` generally mean that the element should take up space on the page but just not show?

I agree with the UI change, but I think we should do it by toggling `display: none` for `#recent-keys`.

2020-09-19 02:19 UTC, mtlynch commented on app/static/js/app.js
> +    document.getElementById("recent-keys").style.removeProperty("display");
Can we use `hideElementById` and `showElementById` instead?

2020-09-19 12:21 UTC, mtlynch commented
Is there any way to bring back the `transition` rule? Without it, the transition looks jerky and undeliberate.

2020-09-19 13:38 UTC, djclueless commented
I do not think you can do a transition on display property, we can do the height like I originally had it or we can do opacity. But it looks like having the display: flex property causes some issues.

https://stackoverflow.com/questions/38772442/css-transition-from-display-none-to-display-block-navigation-with-subnav/38772750

2020-09-23 19:59 UTC, mtlynch approved these changes
LGTM, thanks! Sorry for the delay.

2020-09-23 19:59 UTC, merged