Fix modifier keys that don't work in combination with mouse clicks.
mtlynch/tinypilot pull request #692
Opened 2021-05-13 21:22 UTC by jdeanwallace

`hid.keyboard.send_keystroke` was always releasing the key after it has been pressed. This is because a keycode is not actually set when a modifier is pressed on it's own. This stopped us from doing things like holding in the shift key and clicking with the mouse to highlight text. [Demo video](https://www.loom.com/share/8a4629a3a70f459d9869cd493e04289a).

Fixes #620

2021-05-13 21:28 UTC, mtlynch commented
Nice! Could we add a unit test for this? We should be able to borrow a lot of the structure from `mouse_test.py`:

https://github.com/mtlynch/tinypilot/blob/34d8d4fd7b6f06b35e58690c3a8a2c0ab73a1fac/app/hid/mouse_test.py

2021-05-14 21:44 UTC, jdeanwallace commented
> Nice! Could we add a unit test for this? We should be able to borrow a lot of the structure from `mouse_test.py`:
> 
> https://github.com/mtlynch/tinypilot/blob/34d8d4fd7b6f06b35e58690c3a8a2c0ab73a1fac/app/hid/mouse_test.py

Done.

2021-05-14 22:26 UTC, mtlynch requested changes
> *[Reviewable](https://reviewable.io/reviews/mtlynch/tinypilot/692)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jdeanwallace)

___
*[app/hid/keyboard_test.py, line 11 at r2](https://reviewable.io/reviews/mtlynch/tinypilot/692#-M_gy_LC1661iOPdsBRt:-M_gy_LDDInPT-hfwN2O:b-pnbinu) ([raw file](https://github.com/mtlynch/tinypilot/blob/2ba89ec92feb34f4e6f612b24d3685f46a300b77/app/hid/keyboard_test.py#L11)):*
> ```Python
> class KeyboardTest(unittest.TestCase):
> 
>     @mock.patch.object(keyboard, 'release_keys')
> ```

It's a bit of an anti-pattern to mock out parts of the system that we're testing. Mocking out dependencies is fine if we have to, but mocking out the class' own methods is something I try to avoid.

I don't think it should be too hard to test without the mock. The only challenge is just making it clear in the test that there are two separate HID reports.


<!-- Sent from Reviewable.io -->

2021-05-14 23:04 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/mtlynch/tinypilot/692)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @mtlynch)

___
*[app/hid/keyboard_test.py, line 11 at r2](https://reviewable.io/reviews/mtlynch/tinypilot/692#-M_gy_LC1661iOPdsBRt:-M_h4JJtEq3JdHX_jXn9:b-gcrb08) ([raw file](https://github.com/mtlynch/tinypilot/blob/2ba89ec92feb34f4e6f612b24d3685f46a300b77/app/hid/keyboard_test.py#L11)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

It's a bit of an anti-pattern to mock out parts of the system that we're testing. Mocking out dependencies is fine if we have to, but mocking out the class' own methods is something I try to avoid.

I don't think it should be too hard to test without the mock. The only challenge is just making it clear in the test that there are two separate HID reports.
</blockquote></details>

Thanks, I understand. I was having some trouble testing the HID reports of the normal keystrokes because the `release_keys` kept overwriting the previous keystrokes. This was happening because the [HID file was being opened and writing to the beginning of the file](https://github.com/mtlynch/tinypilot/blob/12f94204299ee4fea36c6667ea09e6d47da24d35/app/hid/write.py#L17). So to get around this I decided to mock the `release_keys` to not interfere with my test.

I now realize that this is a bug. We should always be [appending to the HID file](https://github.com/mtlynch/tinypilot/blob/257107f1a2c257e9272d8618f3ab3b726a7fe3cc/app/hid/write.py#L17).


<!-- Sent from Reviewable.io -->

2021-05-18 13:53 UTC, mtlynch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Thanks!

> *[Reviewable](https://reviewable.io/reviews/mtlynch/tinypilot/692#-:-M_zkDnk2-7dl6KI6uAX:b-41s8zb)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jdeanwallace)



<!-- Sent from Reviewable.io -->

2021-05-18 18:51 UTC, merged